### ISSUE TITLE
Fix tiny typo in docs

### ISSUE THREAD

**Issue by jamilraichouni** [DSD-DBS/capella-polarion#120]
https://github.com/DSD-DBS/capella-polarion/blob/4ec97514411b590a9a693e03f2a7841025186090/docs/source/pipeline%20templates/gitlab.rst?plain=1#L15

should read

```text
We highly recommend using the diagram cache as a separate job and define it as a dependency in our template for that 
```

`define` instead of `dcefined`

**Comment by ewuerger** [comment]
You meant `defined`, hehe. Thank you for the info.
